"""Criação inicial do banco de dados

Revision ID: 124bf0f608d6
Revises: 
Create Date: 2025-03-13 23:49:08.485646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124bf0f608d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('qualis', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('autores', sa.Text(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('publicacao', sa.String(length=200), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('paginas', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('data_acesso', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pesquisador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('lattes_id', sa.String(length=20), nullable=True),
    sa.Column('orcid', sa.String(length=20), nullable=True),
    sa.Column('instituicao_id', sa.Integer(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('titulacao', sa.String(length=50), nullable=True),
    sa.Column('area_atuacao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lattes_id'),
    sa.UniqueConstraint('orcid')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('area_conhecimento', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('financiamento', sa.String(length=100), nullable=True),
    sa.Column('valor_financiamento', sa.Float(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_lembrete', sa.Date(), nullable=True),
    sa.Column('instituicao_id', sa.Integer(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['pesquisador.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('projeto_evento',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('data_participacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('projeto_id', 'evento_id')
    )
    op.create_table('projeto_pesquisador',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('pesquisador_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pesquisador_id'], ['pesquisador.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('projeto_id', 'pesquisador_id')
    )
    op.create_table('projeto_referencia',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['referencia_id'], ['referencia.id'], ),
    sa.PrimaryKeyConstraint('projeto_id', 'referencia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto_referencia')
    op.drop_table('projeto_pesquisador')
    op.drop_table('projeto_evento')
    op.drop_table('projeto')
    op.drop_table('pesquisador')
    op.drop_table('usuario')
    op.drop_table('referencia')
    op.drop_table('instituicao')
    op.drop_table('evento')
    # ### end Alembic commands ###
