"""Adicionar campo is_admin no modelo Usuario

Revision ID: d7173a34c3c7
Revises: 124bf0f608d6
Create Date: 2025-03-16 23:17:52.887001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7173a34c3c7'
down_revision = '124bf0f608d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
